import requests
import json
from pprint import pprint

url = "https://api.unsplash.com/search/photos/"
my_client_id = "?client_id=" #client_id is generated by unsplash for each API user
orientation = "landscape"
search = {"query": "ocean", "per_page": 1}


response = requests.get(url + my_client_id, 
    headers={"Accept-Version": 'v1'}, params = search)

x = json.loads(response.content)

pprint(x)